repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: end-of-file-fixer
        exclude: ^tests/unit/data/
      - id: fix-byte-order-marker
        exclude: ^tests/unit/data/
      - id: mixed-line-ending
        args: ["--fix", "lf"]
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.10
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        exclude: ^docs/source/_templates/
  - repo: https://github.com/crate-ci/typos
    rev: v1.30.2
    hooks:
      - id: typos
        args: ["--force-exclude"]
